version: '3'

services:

  dev:
    container_name: automatic-palm-tree
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app/'
      - '/usr/src/app/node_modules'
    ports:
      - '8080:8080'
      - '8888:8888'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
    command: npm run start
